DROP TABLE VENTAS;
DROP TABLE PRODUCTOS;

-- Tabla de Productos
CREATE TABLE PRODUCTOS (
    PLU VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(100)
);

-- Tabla de Ventas
CREATE TABLE VENTAS (
    SUCURSAL VARCHAR2(10),
    FECHA DATE,
    CAJA VARCHAR2(10),
    TICKET NUMBER,
    PLU VARCHAR2(20),
    IMPORTE NUMBER(12, 2)
);